
#system slock
set_property PACKAGE_PIN Y18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]

#reset active low,S4
set_property PACKAGE_PIN B21 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property PACKAGE_PIN M17 [get_ports {ov5640_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[0]}]
set_property PACKAGE_PIN E1 [get_ports {ov5640_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[1]}]
set_property PACKAGE_PIN D1 [get_ports {ov5640_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[2]}]
set_property PACKAGE_PIN G2 [get_ports {ov5640_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[3]}]
set_property PACKAGE_PIN F1 [get_ports {ov5640_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[4]}]
set_property PACKAGE_PIN H2 [get_ports {ov5640_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[5]}]
set_property PACKAGE_PIN G1 [get_ports {ov5640_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[6]}]
set_property PACKAGE_PIN J1 [get_ports {ov5640_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[7]}]
set_property PACKAGE_PIN J2 [get_ports ov5640_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_pclk]
set_property PACKAGE_PIN B2 [get_ports ov5640_href]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_href]
set_property PACKAGE_PIN M20 [get_ports ov5640_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_vsync]
set_property PACKAGE_PIN A1 [get_ports sccb_sda]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_sda]
set_property PULLUP true [get_ports sccb_sda]
set_property PACKAGE_PIN L18 [get_ports sccb_scl]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_scl]
set_property PULLUP true [get_ports sccb_scl]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov5640_pclk_IBUF]

set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_p]
set_property PACKAGE_PIN K4 [get_ports hdmi_clk_p]
set_property PACKAGE_PIN J4 [get_ports hdmi_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p[0]}]
set_property PACKAGE_PIN L3 [get_ports {hdmi_data_p[0]}]
set_property PACKAGE_PIN K3 [get_ports {hdmi_data_n[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_n[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p[1]}]
set_property PACKAGE_PIN L5 [get_ports {hdmi_data_p[1]}]
set_property PACKAGE_PIN L4 [get_ports {hdmi_data_n[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_n[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p[2]}]
set_property PACKAGE_PIN M3 [get_ports {hdmi_data_p[2]}]
set_property PACKAGE_PIN M2 [get_ports {hdmi_data_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_n[2]}]
set_property PACKAGE_PIN H5 [get_ports hdmi_oe]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_oe]



connect_debug_port u_ila_0/probe2 [get_nets [list {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_len[0]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_len[1]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_len[2]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_len[3]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_len[4]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_len[5]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_len[6]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_len[7]}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_clk]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 28 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[0]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[1]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[2]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[3]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[4]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[5]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[6]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[7]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[8]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[9]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[10]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[11]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[12]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[13]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[14]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[15]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[16]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[17]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[18]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[19]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[20]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[21]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[22]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[23]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[24]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[25]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[26]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_addr[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 64 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[0]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[1]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[2]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[3]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[4]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[5]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[6]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[7]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[8]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[9]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[10]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[11]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[12]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[13]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[14]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[15]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[16]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[17]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[18]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[19]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[20]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[21]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[22]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[23]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[24]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[25]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[26]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[27]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[28]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[29]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[30]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[31]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[32]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[33]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[34]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[35]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[36]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[37]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[38]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[39]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[40]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[41]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[42]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[43]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[44]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[45]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[46]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[47]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[48]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[49]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[50]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[51]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[52]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[53]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[54]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[55]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[56]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[57]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[58]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[59]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[60]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[61]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[62]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_data[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/wr_clk ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_clk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 28 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[0]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[1]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[2]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[3]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[4]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[5]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[6]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[7]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[8]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[9]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[10]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[11]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[12]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[13]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[14]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[15]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[16]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[17]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[18]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[19]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[20]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[21]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[22]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[23]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[24]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[25]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[26]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_addr[27]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 64 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[0]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[1]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[2]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[3]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[4]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[5]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[6]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[7]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[8]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[9]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[10]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[11]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[12]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[13]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[14]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[15]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[16]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[17]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[18]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[19]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[20]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[21]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[22]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[23]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[24]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[25]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[26]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[27]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[28]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[29]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[30]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[31]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[32]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[33]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[34]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[35]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[36]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[37]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[38]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[39]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[40]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[41]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[42]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[43]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[44]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[45]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[46]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[47]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[48]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[49]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[50]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[51]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[52]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[53]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[54]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[55]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[56]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[57]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[58]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[59]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[60]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[61]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[62]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_data[63]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 11 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[0]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[1]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[2]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[3]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[4]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[5]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[6]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[7]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[8]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[9]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_rd_fifo_wrport[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 11 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[0]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[1]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[2]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[3]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[4]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[5]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[6]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[7]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[8]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[9]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/cnt_wr_fifo_rdport[10]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[0]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[1]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[2]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[3]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[4]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[5]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[6]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[7]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[8]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[9]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[10]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[11]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[12]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[13]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[14]} {ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/rd_data[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 9 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_done ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_ready ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_wr_start ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_writing ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_done ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_ready ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rd_start ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_reading ddr_interface_inst/u_axi_ddr_ctrl/axi_ctrl_inst/axi_rst_n]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_axi_clk]
