
#system slock
set_property PACKAGE_PIN Y18 [get_ports sys_clk]
set_property IOSTANDARD LVCMOS33 [get_ports sys_clk]

#reset active low,S4
set_property PACKAGE_PIN B21 [get_ports sys_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sys_rst_n]

set_property PACKAGE_PIN M17 [get_ports {ov5640_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[0]}]
set_property PACKAGE_PIN E1 [get_ports {ov5640_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[1]}]
set_property PACKAGE_PIN D1 [get_ports {ov5640_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[2]}]
set_property PACKAGE_PIN G2 [get_ports {ov5640_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[3]}]
set_property PACKAGE_PIN F1 [get_ports {ov5640_data[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[4]}]
set_property PACKAGE_PIN H2 [get_ports {ov5640_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[5]}]
set_property PACKAGE_PIN G1 [get_ports {ov5640_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[6]}]
set_property PACKAGE_PIN J1 [get_ports {ov5640_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov5640_data[7]}]
set_property PACKAGE_PIN B1 [get_ports ov5640_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_rst_n]
set_property PACKAGE_PIN J2 [get_ports ov5640_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_pclk]
set_property PACKAGE_PIN B2 [get_ports ov5640_href]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_href]
set_property PACKAGE_PIN M20 [get_ports ov5640_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports ov5640_vsync]
set_property PACKAGE_PIN A1 [get_ports sccb_sda]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_sda]
set_property PULLUP true [get_ports sccb_sda]
set_property PACKAGE_PIN L18 [get_ports sccb_scl]
set_property IOSTANDARD LVCMOS33 [get_ports sccb_scl]
set_property PULLUP true [get_ports sccb_scl]

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov5640_pclk_IBUF]

set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_p]
set_property PACKAGE_PIN K4 [get_ports hdmi_clk_p]
set_property PACKAGE_PIN J4 [get_ports hdmi_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p[0]}]
set_property PACKAGE_PIN L3 [get_ports {hdmi_data_p[0]}]
set_property PACKAGE_PIN K3 [get_ports {hdmi_data_n[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_n[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p[1]}]
set_property PACKAGE_PIN L5 [get_ports {hdmi_data_p[1]}]
set_property PACKAGE_PIN L4 [get_ports {hdmi_data_n[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_n[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_p[2]}]
set_property PACKAGE_PIN M3 [get_ports {hdmi_data_p[2]}]
set_property PACKAGE_PIN M2 [get_ports {hdmi_data_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_data_n[2]}]
set_property PACKAGE_PIN H5 [get_ports hdmi_oe]
set_property IOSTANDARD LVCMOS33 [get_ports hdmi_oe]

set_property PACKAGE_PIN M22 [get_ports led_display[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led_display[0]]
set_property PACKAGE_PIN N22 [get_ports led_display[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led_display[1]]
set_property PACKAGE_PIN L21 [get_ports led_display[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led_display[2]]
set_property PACKAGE_PIN K21 [get_ports led_display[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led_display[3]]
